services:
  web:
    build: ./web
    ports:
      - "2137:2137"
    networks:
      - transnet
  minio:
    image: minio/minio:latest
    ports:
      - "9001:9001"
      - "9000:9000"
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
    volumes:
      - ./minio/data:/data:rw
    command: server /data --console-address ":9001" 

networks:
  transnet:
