services:
  web:
    build: ./web
    ports:
      - "2137:2137"
    networks:
      - transnet
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
      MINIO_ADDRESS: minio:9000
      RABBITMQ_ADDRESS: rabbit
      REDIS_ADDRESS: redis:6379

  backapp:
    build: ./backapp
    networks:
      - transnet
    environment:
      RABBITMQ_ADDRESS: rabbit
      POSTGRES_ADDRESS: postgres
    env_file:
      - ./.postgres.env
      
  minio:
    image: minio/minio:latest
    ports:
      - "9001:9001"
      - "9000:9000"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - ./minio/data:/data:rw
    command: server /data --console-address ":9001" --address ":9000"
    networks:
      - transnet

  rabbit:
    image: rabbitmq:3-management-alpine
    container_name: translation-rabbitmq
    ports:
      - "15672:15672"
    networks:
      - transnet

  redis:
    image: redis:7-alpine
    container_name: translatino_redis
    networks:
      - transnet
  
  postgres:
    image: postgres:latest
    networks:
      - transnet
    env_file:
      - ./.postgres.env

  pgadmin:
    image: dpage/pgadmin4:latest
    networks:
      - transnet
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "3000:80"

networks:
  transnet:
