# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: crud.proto
# Protobuf Python Version: 5.27.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    1,
    '',
    'crud.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ncrud.proto\x12\x08messages\x1a\x1fgoogle/protobuf/timestamp.proto\"d\n\x08NewOrder\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12(\n\x04\x64\x61te\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\xee\x01\n\x0fOrderStatusInfo\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x19\n\x11\x63lientDescription\x18\x03 \x01(\t\x12/\n\x0b\x64\x61teOrdered\x18\x04 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12/\n\x0blastUpdated\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12%\n\x06status\x18\x08 \x01(\x0e\x32\x15.messages.OrderStatus\x12\x12\n\x05price\x18\x07 \x01(\x03H\x00\x88\x01\x01\x42\x08\n\x06_price\"\x16\n\x08GetOrder\x12\n\n\x02id\x18\x01 \x01(\t*u\n\x0bOrderStatus\x12\x18\n\x14ORDER_STATUS_CREATED\x10\x00\x12\x17\n\x13ORDER_STATUS_PRICED\x10\x01\x12\x1c\n\x18ORDER_STATUS_IN_PROGRESS\x10\x02\x12\x15\n\x11ORDER_STATUS_DONE\x10\x03\x42\x0bZ\t/messagesb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'crud_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\t/messages'
  _globals['_ORDERSTATUS']._serialized_start=424
  _globals['_ORDERSTATUS']._serialized_end=541
  _globals['_NEWORDER']._serialized_start=57
  _globals['_NEWORDER']._serialized_end=157
  _globals['_ORDERSTATUSINFO']._serialized_start=160
  _globals['_ORDERSTATUSINFO']._serialized_end=398
  _globals['_GETORDER']._serialized_start=400
  _globals['_GETORDER']._serialized_end=422
# @@protoc_insertion_point(module_scope)
